FROM python:3.10.0-slim

WORKDIR /usr/backend
ENV PYTHONPATH /usr/backend/src

COPY poetry.lock ./
COPY pyproject.toml ./

RUN pip install poetry
RUN poetry install --no-interaction --no-ansi


COPY . .

CMD ["poetry", "run", "uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]